version: '3.8'

services:
  app:
    build: .
    ports:
      - "127.0.0.1:8082:8082"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - TELEGRAM_API_ID=${TELEGRAM_API_ID}
      - TELEGRAM_API_HASH=${TELEGRAM_API_HASH}
    volumes:
      - telegram_session:/app/data/telegram_session
      - db_data:/app/data/db
    stdin_open: true
    tty: true
    restart: unless-stopped

volumes:
  telegram_session:
    name: telegram_classifier_session
  db_data:
    name: telegram_classifier_db