version: '3.8'

services:
  app:
    build: .
    ports:
      - "127.0.0.1:8082:8082"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - TELEGRAM_API_ID=${TELEGRAM_API_ID}
      - TELEGRAM_API_HASH=${TELEGRAM_API_HASH}
      - TELEGRAM_PHONE=${TELEGRAM_PHONE}
    volumes:
      - .:/app
      - ./telegram_session:/app/telegram_session
    stdin_open: true
    tty: true