version: '3.8'

services:
  app:
    build: .
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - TELEGRAM_API_ID=${TELEGRAM_API_ID}
      - TELEGRAM_API_HASH=${TELEGRAM_API_HASH}
    volumes:
      - telegram_session:/app/data/telegram_session
      - db_data:/app/data/db
      - ./logs:/app/logs
    stdin_open: true
    tty: true
    restart: unless-stopped
    networks:
      - shared_network

volumes:
  telegram_session:
    name: telegram_classifier_session
  db_data:
    name: telegram_classifier_db

networks:
  shared_network:
    external: true
